apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextchat.fullname" . }}
  labels:
    {{- include "nextchat.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nextchat.selectorLabels" . | nindent 4 }}
